<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPJmZLAC\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPJmZLAC/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerPJmZLAC.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerPJmZLAC\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerPJmZLAC\appAppKernelProdContainer([
    'container.build_hash' => 'PJmZLAC',
    'container.build_id' => '937a37f7',
    'container.build_time' => 1709982295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPJmZLAC');
